name: samovar
channels:
  - conda-forge
  - bioconda
#  - pytorch
dependencies:
  - insilicoseq=1.5.4
  - python=3.10
  - pip=23.1.2
  - pip:
      - pandas==2.0.1
      - numpy==1.24
      - biopython==1.80
      - python-sat==0.1.8.dev3
      - scipy==1.10.1
      - pysam==0.21.0
      - future==0.18.3
      - joblib==1.2.0
      - pyyaml==6.0
#      - cpuonly
#      - pytorch==2.0.1
